---
- hosts: all
  become: True
  gather_facts: no
  tasks: 
    - name: Get Os name
      shell: awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"'
      register: os_info

    - name: "Create a group"
      group: 
        name: "{{ item }}"
        state: present
      with_items:
        - devops
        - dev
        - qa
        
    - name: "Create a user BANGA on servers"
      user: 
        name: BANGA
        comment: BANGA kef
        groups: devops, dev
        shell: /bin/bash
    
    - name: "Create a directory"
      file:
        path: /root/my_created_dir
        state: directory

    - name: "Create a file"
      file:
        path: /root/my_created_dir/my_created_file.txt
        state: touch
    
    - name: Print OS name
      debug:
        msg: "This OS name is : {{os_info.stdout}}" 
    
    - name: "Install httpd on Centos"
      yum:
        name: httpd
        state: present
      when: os_info.stdout == "CentOS Stream"
    - name: Run httpd
      service:
        name: httpd
        state: started
        enabled: yes
      when: os_info.stdout == "CentOS Stream"

    - name: "Install nginx on Ubuntu"
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: os_info.stdout == "Ubuntu"

    - name: "Add content to file created"
      copy:
        dest: /root/my_created_dir/my_created_file.txt
        content: <h1>THIS IS THE NEW <b>KEFKY</b> PAGE</h1>
    - name: "Change page content"
      copy:
        src: /root/my_created_dir/my_created_file.txt
        dest: /usr/share/nginx/html/index.html
        remote_src: yes
      when: os_info.stdout == "Ubuntu"
    - name: "Change page content"
      copy:
        src: /root/my_created_dir/my_created_file.txt
        dest: /var/www/html/index.html
        remote_src: yes
      when: os_info.stdout == "CentOS Stream"
    # - name: "Patch servers"
    #   yum:
    #     name: '*'
    #     state: latest
    #   when: 
